version: "3.8"

services:
  blogsphere.search.api:
    container_name: Blogsphere.Search.Api
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - Logging__IncludeScopes=false
      - "Logging__LogOutputTemplate=[{Timestamp:dd-MM-yyyy HH:mm:ss, fff}] {Level} {Properties} [CorrelationId:{CorrelationId}] [Machine: {MachineName}] {CallerType}:{MemberName} {Message}{NewLine}{Exception}{NewLine} {NewLine}"
      - Logging__Console__Enabled=true
      - Logging__Console__LogLevel=Debug
      - Logging__Elastic__Enabled=true
      - Logging__Elastic__LogLevel=Debug
      - AppConfigurations__ApplicationIdentifier=Blogsphere.Search.Api
      - AppConfigurations__ApplicationEnvironment=docker
      - AppConfigurations__HealthCheckTimeOutInSeconds=30
      - ApiDescription=Blogsphere Search API
      - ApiOriginHost=localhost:8002
      - HealthcheckUrl=http://localhost:8080/healthcheck
      - ElasticSearch__Uri=http://elasticsearch:9200
      - ElasticSearch__ApiClusterIndex=apicluster-search-index
      - ElasticSearch__ApiRouteIndex=apiroute-search-index
      - ElasticSearch__ManagementUserIndex=managementuser-search-index
      - IdentityGroupAccess__Authority=http://host.docker.internal:5000
      - IdentityGroupAccess__Audience=blogsphere.search.api
      - EventBus__Host=rabbitmq
      - EventBus__Username=guest
      - EventBus__Password=guest
      - EventBus__VirtualHost=/
      - EventBus__Port=5672
      - "ConnectionStrings__BlogsphereStorageConnection=DefaultEndpointsProtocol=http;AccountName=blogspherestrg;AccountKey=123e4567e89b12d3a456426614174000;BlobEndpoint=http://host.docker.internal:10000/blogspherestrg;QueueEndpoint=http://host.docker.internal:10001/blogspherestrg;TableEndpoint=http://host.docker.internal:10002/blogspherestrg;"
      - Zipkin__Url=http://zipkin:9411/api/v2/spans
      - ProviderSettings__ApiGatewaySettings__BaseUrl=http://host.docker.internal:8000
      - ProviderSettings__ApiGatewaySettings__ClientId=blogshere.apigateway.api
      - ProviderSettings__ApiGatewaySettings__ClientSecret=apigateway-secret-key-2024
      - ProviderSettings__UserApiSettings__BaseUrl=http://host.docker.internal:8000/user/
      - ProviderSettings__UserApiSettings__ClientId=blogshere.user.api
      - ProviderSettings__UserApiSettings__ClientSecret=user-secret-key-2024
      - ProviderSettings__UserApiSettings__SubscriptionKey=efc2253f-6d87-40bb-9623-88c0e2bbaa4b
      - Jaeger__Host=localhost
      - Jaeger__Port=6831
    ports:
      - "8002:8080"
    networks:
      - blogsphere_dev_net
